_target_: src.models.blip_kb.BlipKb

lr: 0.001
weight_decay: 0.05
num_warmup_steps: 700
dropout_prob: 0.4
model_path: /home/anbinx/.cache/models--blip-base/model_base.pth
med_config: /home/anbinx/.cache/models--blip-base/med_config.json
fc_hidden_size: 256
cnn_embedding_dim: 300
cnn_conv_out_channels: 128
cnn_kernel_sizes: [3, 4, 5]
cnn_dropout_prob: 0.4
cnn_hidden_size: 64
cnn_output_size: 768
is_freeze_blip: true
fine_tune_visual_encoder: false
fine_tune_text_encoder: true
