_target_: src.models.blip_kb.BlipKb

lr: 0.001
weight_decay: 0.05
num_warmup_steps: 700
dropout_prob: 0.4
model_path: /home/anbinx/.cache/models--blip-base/model_base.pth
med_config: /home/anbinx/.cache/models--blip-base/med_config.json
fc_hidden_size: 256
#kb_encoder:
#  _target_: src.models.blip_kb.TextCNN
#  embedding_dim: 300
#  conv_out_channels: 128
#  kernel_sizes: [3, 4, 5]
#  dropout_prob: 0.4
#  hidden_size: 64
#  output_size: 768
kb_encoder:
  _target_: src.models.blip_kb.LstmEncoder
  input_size: 300
  num_layers: 2
  hidden_size: 256
  bidirectional: true
  dropout_prob: 0.4
  fc_hidden_size: 256
is_freeze_blip: true
fine_tune_visual_encoder: false
fine_tune_text_encoder: true
