_target_: src.models.simple_blip.SimpleBlip

lr: 0.001
weight_decay: 0.05
num_warmup_steps: 700
dropout_prob: 0.5
model_path: /root/.cache/models--blip-base/model_base.pth
med_config: /root/.cache/models--blip-base/med_config.json
fc_hidden_size: 2048
