_target_: src.datamodules.fake_news_data.MultiModalData

img_path: ${paths.data_dir}/image-verification-corpus-master/images_filtered
dataset_name: twitter
tokenizer_name: bert-base-uncased
processor_name: null
train_path: ${paths.data_dir}/image-verification-corpus-master/train_posts.json
test_path: ${paths.data_dir}/image-verification-corpus-master/test_posts.json
max_length: 23
val_set_ratio: 0.1
batch_size: 8
num_workers: 0
use_test_as_val: true
simclr_trans: false
vis_model_type: vgg
