_target_: src.datamodules.fake_news_data.MultiModalData

img_path: /root/fake_news_detection/data/image-verification-corpus-master/images_filtered
dataset_name: twitter
tokenizer_name: bert-base-multilingual-cased
processor_name: null
train_path: /root/fake_news_detection/data/image-verification-corpus-master/train_posts.json
test_path: /root/fake_news_detection/data/image-verification-corpus-master/test_posts.json
max_length: 200
val_set_ratio: 0.1
batch_size: 32
num_workers: 0
