_target_: src.datamodules.fake_news_data.MultiModalData

img_path: ${paths.data_dir}/MM17-WeiboRumorSet/images_filtered
dataset_name: weibo_with_event
tokenizer_name: bert-base-chinese
processor_name: null
train_path: ${paths.data_dir}/weibo/train_data.json
val_path: ${paths.data_dir}/weibo/val_data.json
test_path: ${paths.data_dir}/weibo/test_data.json
max_length: 200
val_set_ratio: 0.1
batch_size: 32
num_workers: 0
use_test_as_val: false
vis_model_type: vgg
